import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/Navbar'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <styles></styles>
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          For full details, visits <a href="https://www.linkedin.com/in/supawat-suntornlimsiri-297375205/">LinkedIn</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://my-documentation-eta.vercel.app/projects/" className={styles.card}>
            <h2>My Documentation Site &rarr;</h2>
            <p>See the past present and future profile of my career</p>
          </a>

          <a href="https://my-documentation-eta.vercel.app/blog/" className={styles.card}>
            <h2>My Interests &rarr;</h2>
            <p>Hobby, News and My interested issue around the world</p>
          </a>

          <a className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            <Image></Image>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}